### ISSUE TITLE
Auto-renewable verification always returns purchased or notPurchases, not expired

### ISSUE THREAD

**Issue by arm0nic** [bizz84/SwiftyStoreKit#114]
### Platform

- [x] iOS

### In app purchase type

- [x] Auto-Renewable Subscription

### Environment

- [x] Sandbox

### Version
0.6.1

### Issue summary

I am trying to verify an auto-renewable subscription but for some reason verifySubscription always returns purchased even though the subscription is already expired. I am not sure if the problem lies on my end but I tried different ways of verification and they all seem to fail.

First try: returns purchased(expiryDate:)
``` swift
let verificationResult = SwiftyStoreKit.verifySubscription(productId: advertisementIdentifier, inReceipt: receipt)
                
switch verificationResult {
     case .purchased(expiryDate: let date):
          return .purchased(expiryDate: date)
     case .expired(expiryDate: _):
          return .expired
     case .notPurchased:
          return .notPurchased
}
```

Second try: returns purchased(expiryDate:)

``` swift
let verificationResult = SwiftyStoreKit.verifySubscription(productId: advertisementIdentifier, inReceipt: receipt)
                
switch verificationResult {
     case .purchased(expiryDate: let date):
          let secondVerificationResult = SwiftyStoreKit.verifySubscription(productId: advertisementIdentifier, inReceipt: receipt, validUntil: date)
                    
          switch secondVerificationResult {
               case .purchased(expiryDate: let expiryDate):
                    return .purchased(expiryDate: expiryDate)
               default:
                    return .expired
          }
     default:
           return .notPurchased
}
```

What I ended up doing now is:

``` swift
let verificationResult = SwiftyStoreKit.verifySubscription(productId: advertisementIdentifier, inReceipt: receipt)
                
switch verificationResult {
case .purchased(expiryDate: let expiryDate):
     if expiryDate.isInFuture() {
          return .purchased(expiryDate: expiryDate)
     }
     return .expired
default:
     return .notPurchased
}
```

It is working but in my opinion verifySubscription should also return expired instead of purchased.

Nevertheless, thank you so much for this great framework! Really saved me lots of time :)

**Comment by bizz84** [comment]
@arm0nic Apologies for the late response.

I have been doing some tests with the sandbox. First, I purchased an auto renewable subscription.

Then, I called the `verifySubscription` method and verified the expiry date. In my test, this value was:

`2017-02-05 07:19:25 +0000`

I then observed the following:

* Because the receipt date **is less** than the expiry time, SwiftyStoreKit returns `.purchased(let expiryDate)`
* If I call again `verifySubscription` after `2017-02-05 07:19:25 +0000`, I get a new expiry date:

`2017-02-05 07:22:25 +0000`

As a result, SwiftyStoreKit returns `.purchased(let expiryDate)` again.

I have repeated this a few times, and observed that the expiry date in the receipt is pushed back by 3 minutes, up until 15 minutes past the initial expiry date for my purchase:

`2017-02-05 07:34:25 +0000`

After that, calling `verifySubscription` again results in `.expired(let expiryDate)` where `expiryDate == 2017-02-05 07:34:25 +0000`.

I believe this is a specific behaviour implemented by Apple for sandbox receipts.

I guess that in production there should only ever be one expiry date for each purchase, however please verify this on your side.

**Comment by bizz84** [comment]
Also, this could be related to this: https://github.com/bizz84/SwiftyStoreKit/issues/129

Please retest on version 0.7.1.

**Comment by bizz84** [comment]
@arm0nic let me know if this is working for you.

I will close this issue in the next couple of weeks if there are no updates.

**Comment by arm0nic** [comment]
Thanks @bizz84 for you detailed answer! I will try to test you suggestions and get back to you if it is working or not :)

**Comment by bizz84** [comment]
@arm0nic closing this for now. Feel free to reopen if you experience the same problems.
