### ISSUE TITLE
Add Code Linting

### ISSUE THREAD

**Issue by bizz84** [bizz84/SwiftyStoreKit#139]
This will make it easier to standardize contributions to the project and make them easier to review and accept.

Could use one of the following: 

* https://github.com/realm/SwiftLint
* https://github.com/nicklockwood/SwiftFormat

**Comment by phimage** [comment]
You cannot use the two tools at same time without configuring it 
for instance they disagree about last comma in array (so if you use the two, you must deactivate some rules)

I think swiftlint is a better choice because it is 'lint', not only format
 (swiftformat do better with some space between parenthesis, maybe one pass can be done)

for a first step do a `swiftlint autocorrect`

then to test yesterday I add a .swiftlint.yml file  with inside line_length: 250
see https://github.com/phimage/SwiftyStoreKit/commit/7250f19d30fd4f1aa54a4b4b0af39b322f3db541
I add also build phrase script 

there is 
- some comment to break
- some vars to rename in test and demo (real compil error with swiftlint)

**Comment by RiverbayChris** [comment]
I vote for swiftlint!

**Comment by tbaranes** [comment]
+1 for SwiftLint

**Comment by bizz84** [comment]
@phimage Totally impressed with swiftlint. I set it up and fixed all linting errors in half hour!

Will use it on all my projects from now on! Thanks everyone for recommending it 💯

**Comment by bizz84** [comment]
Available on version 0.8.1
