### ISSUE TITLE
Purchase Failed, invalid product ID, but it is 100% correct

### ISSUE THREAD

**Issue by mrmasterwill** [bizz84/SwiftyStoreKit#177]
### Platform

- iOS

### In app purchase type
- Non-consumable 

### Environment

- Sandbox

### Version
Most current

### Issue summary
When I press on my button to buy the nonrenewable it says that "Purchase Failed", "The purchase identifier was invalid" and in the debugger it tells me the same and prints out my product ID. Yet the product ID is totally correct.

Please help, am I doing something stupid?

**Comment by mrmasterwill** [comment]
I've now directly copied the demo code in and obviously changed code where necessary and I still get the exact same error

**Comment by vaibhav-varshaaweblabs** [comment]
@mrmasterwill Same here
My Non Consumable product is always listed under Invalid Product ID's

**Comment by CaptainYukinoshitaHachiman** [comment]
Same here
So what's the coder doing?

**Comment by bizz84** [comment]
Please see #154. This has been discussed in detail there.

**Comment by bizz84** [comment]
If this is still a problem please continue the discussion on #154. Closing as duplicate for now.

**Comment by DADOFKILL123** [comment]
Hello, I was in the same situation as you guys, the solution for me was simple : The productID is not "BundleID.iAPProductID" but is simply "ProductID". Assuming that you have the correct app-secret , bundler identifier and iAP correctly configured in both developer portal and xcode , you should be able to test in sandbox environment before submitting to the appStore

**Comment by soenkegissel** [comment]
Just as a reminder to complete the 'Agreements, Tax and Banking' in iTunes connect first. 
That was the problem for me.
![image](https://user-images.githubusercontent.com/13346316/53948376-f97e8a00-40c7-11e9-92b2-4ed967a9087f.png)

**Comment by VictorZhang2014** [comment]
The problem was solved by App Store Connect itself. It was a new app submitted to App Store, after approved, there was only one non-renewal consumable item could work.
Originally, the app has 6 items with `non-renewal consumable` plan. After it approved, I thought my code was wrong somewhere, but 8 hours later, all 6 items could work, and the process of In-App Purchases was running well. I guess this is the time in force without doubtlessly.

![image](https://user-images.githubusercontent.com/6853884/108798099-e53f3a80-75c7-11eb-880e-380d4e6ff15a.png)
