### ISSUE TITLE
unhandledTransactions ... message

### ISSUE THREAD

**Issue by Demetriy** [bizz84/SwiftyStoreKit#179]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [x] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

### Version
0.8.4

### Issue summary
About last 2-3 months, when I try to buy non-consumable (didn't try others) product in log i got message like "unhandledTransactions ...", previously I didn't saw messages like this. I thought that maybe i have outdated api code, but today downloaded example code and saw same message in logs.

### What did you expect to happen
Expect to not see this message.

**Comment by bizz84** [comment]
@Demetriy thanks for reporting this. It is a known message that appears when the payment queue receives a transaction in the `purchasing` state.

Nothing to worry about. The transaction is subsequently updated with a `failed`, `restored` or `purchased` state (which is reported to the caller).

**Note**: It would make sense filter out any transactions in `purchasing` state so that this message is no longer shown.

**Comment by bizz84** [comment]
This was fixed on release 0.9.2. Closing.
