### ISSUE TITLE
Difference between refreshReceipt and restorePurchases

### ISSUE THREAD

**Issue by alexdenk** [bizz84/SwiftyStoreKit#207]
Hello,

I'm trying to understand the difference between the "SwiftyStoreKit.refreshReceipt" and "SwiftyStoreKit.restorePurchases" calls, as in result to the receipt in the bundle.

"SwiftyStoreKit.restorePurchases" is also updating the receipt in the bundle ? 

Thank you

**Comment by bizz84** [comment]
@alexdenk I think this guide from Apple may help you:

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Restoring.html#//apple_ref/doc/uid/TP40008267-CH8-SW9

Quoting:

> In most cases, all your app needs to do is refresh its receipt and deliver the products in its receipt. The refreshed receipt contains a record of the user’s purchases in this app, on this device or any other device.

This is what happens when you call `refreshReceipt()`.

> Restoring completed transactions creates a new transaction for every completed transaction the user made, essentially replaying history for your transaction queue observer. 

This is what happens when you call `restorePurchases()`.

As SwiftyStoreKit doesn't (yet) support local receipt validation, the only way to read the receipt is to call `refreshReceipt()`, which always updates the receipt in the bundle.

Does this answer your question?

**Comment by alexdenk** [comment]
Excellent, thanks
