### ISSUE TITLE
How to get receipt

### ISSUE THREAD

**Issue by ashishfission** [bizz84/SwiftyStoreKit#241]
### Platform

- [* ] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [* ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [* ] Sandbox
- [ ] Production

### Version
ℹ Please replace this with the version of SwiftyStoreKit you're using.

### Related issues
ℹ How to get Apple Receipt
### Issue summary
ℹ I want to send apple receipt to server and also want see human readable receipt.

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by mihai8804858** [comment]
To get receipt data, use 
```swift
if let receiptData = SwiftyStoreKit.localReceiptData {
   let receiptDataAsString = receiptData.base64EncodedString(options: [])
}
``` 
or 
```swift
if let receiptURL = Bundle.main.appStoreReceiptURL, 
   let receiptData = try? Data(contentsOf: receiptURL) {
   let receiptDataAsString = receiptData.base64EncodedString(options: [])
}
```

In order to see human readable receipt content, you should use iTunes Store to parse the receipt, as iTunes Store is the only source of truth when dealing with subscriptions. https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html
You should make a request to `https://buy.itunes.apple.com/verifyReceipt` with your receipt data to get the receipt content.

**Comment by bizz84** [comment]
@ashishfission @mihai8804858 I would also recommend to read the [Receipt Verification](https://github.com/bizz84/SwiftyStoreKit#receipt-verification) section.

To get a human readable receipt in SwiftyStoreKit, you can use the [`verifyReceipt()`](https://github.com/bizz84/SwiftyStoreKit#verify-receipt) method.

Closing this. Feel free to reopen if you have any more questions.
