### ISSUE TITLE
Restore issue with v0.2.7

### ISSUE THREAD

**Issue by atjason** [bizz84/SwiftyStoreKit#25]
Just create a new test account and then try to restore, will get this issue. In this case should return that no purchase was found. But I'm not sure it's caused by Apple's cache or not.

**Comment by atjason** [comment]
Update with v0.2.7:

- In `processRestoreResults`, why still treat `.Purchased` as restore failed?

- If try to restore with an account which hasn't purchase any product, the code come to case of `result.restoreFailedProducts.count > 0`, the error information is like `Error code: 0. Unknown Error.`. It means the code will never run into the branch of `Nothing to Restore`.

- If try to restore with an account which has purchase 2 products, get the result of no product ever purchased. I guess it should be caused by the `isPurchaseRequest` in `.Purchased` which let the code ignore the transaction (it's restore transaction, not purchase transaction), and then the code thought no products were bought.
![restorefailed01](https://cloud.githubusercontent.com/assets/803199/14881523/f1671946-0d66-11e6-8cf6-cbdb56546d62.jpg)
![restorefailed02](https://cloud.githubusercontent.com/assets/803199/14881525/f2b75586-0d66-11e6-97b5-2a71b9ae928c.jpg)

- In your demo of 'alertForRestorePurchases', doesn't deal with the case user cancel purchasing.

**Comment by bizz84** [comment]
Sorry just catching up with this and related issues now. Will try to take a look tomorrow/Monday.

**Comment by bizz84** [comment]
# SwiftyStoreKit fixes

Haven't tested this on OS X yet so my answers are limited to the behaviour I observed on iOS. That being said, in answer to your questions:

- In `processRestoreResults`, why still treat `.Purchased` as restore failed?

Starting on v0.2.7, SwiftyStoreKit should never return `.Purchased` when `processRestoreResults` is called. If this is still happening please file a bug.

- If try to restore with an account which hasn't purchase any product, the code come to case of `result.restoreFailedProducts.count > 0`, the error information is like `Error code: 0. Unknown Error.`. It means the code will never run into the branch of `Nothing to Restore`.

Note that the `NothingToRestore` case no longer exists. Client code should treat `restoredProductIds.count == 0` as the condition for nothing to restore. `Error code: 0. Unknown Error.` is used when a transaction in the payment queue is `.Failed` but there is no error from StoreKit. I still need to do some testing on OS X to try to work out when this happens.


- If try to restore with an account which has purchase 2 products, get the result of no product ever purchased. I guess it should be caused by the `isPurchaseRequest` in `.Purchased` which let the code ignore the transaction (it's restore transaction, not purchase transaction), and then the code thought no products were bought.

This works fine on iOS: I get one restore callback with both products. Need to test on OS X

- In your demo of 'alertForRestorePurchases', doesn't deal with the case user cancel purchasing.

On OS X, does the `restoreCompletedTransactionsFailedWithError` method get called when the user cancels?

As I said, I need to do some testing on OS X and will report back with my findings.

**Comment by atjason** [comment]
@bizz84 Update: with version 0.2.10, the other issues mentioned in this issue were all fixed. So I close it.
