### ISSUE TITLE
Question about InAppReceiptRefreshRequest 

### ISSUE THREAD

**Issue by Cemeter** [bizz84/SwiftyStoreKit#251]
### Platform

- [ ] iOS
### In app purchase type
- [ ] Auto-Renewable Subscription

### Environment

- [ ] Sandbox
- [ ] Production

### Version
v0.10.4

### Related issues
Couldn't find any.

### Issue summary
SwiftyStoreKit.localReceiptData
I find some users using my apps, get a nil value use this methods. I think the best way to solve this question is to refresh the receiptdata when i check it was nil. So please open the InAppReceiptRefreshRequest that i can get it , when i simultaneous use cocoapods.

### What did you expect to happen
SwiftyStoreKit.localReceiptData return nil value

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by stefanomondino** [comment]
I've also started to experience same exact behavior today. The localReceiptData is nil after a purchase, so basically I'm sending a nil receipt to a remote server for validation. Which, of course, always fails.

**Comment by bizz84** [comment]
## Short Answer

Use [`verifyReceipt`](https://github.com/bizz84/SwiftyStoreKit#verify-receipt).

## Long Answer

I would expect that after you complete a purchase, the `localReceiptData` is not nil.

However, if this is not the case, SwiftyStoreKit can't do anything about it because `localReceiptData` simply reads the receipt from the bundle.

In any case, `localReceiptData` is always encrypted, so you need to call `verifyReceipt` anyway to get a readable receipt. 

`verifyReceipt` will take care of refreshing the receipt if it's missing so it solves this problem for you.

**Comment by bizz84** [comment]
@Cemeter @stefanomondino I'm going to close this issue. If you have any more questions, feel free to comment/reopen.
