### ISSUE TITLE
How is storing the shared secret password safe?

### ISSUE THREAD

**Issue by San-Jeevan** [bizz84/SwiftyStoreKit#263]
The new version of this component requires shared apple password as input parameter to verify receipt. If someone reverse engineer the binary they can retrieve the password and use it for malicious purposes!!

the shared secret is supposed to be used on own server for verifying receipts

**Comment by bizz84** [comment]
@San-Jeevan SwiftyStoreKit simply provides a way to send the shared secret to the Apple endpoints ([https://buy.itunes.apple.com/verifyReceipt](https://buy.itunes.apple.com/verifyReceipt) and [https://sandbox.itunes.apple.com/verifyReceipt](https://sandbox.itunes.apple.com/verifyReceipt)) when verifying the receipt.

This is done in the [AppleReceiptValidator](https://github.com/bizz84/SwiftyStoreKit/blob/master/SwiftyStoreKit/AppleReceiptValidator.swift) class, which is simply a reference implementation for how to do receipt validation with Apple.

Sounds like I should clarify this in the README so that users are aware of any security implications and quote any recommendations by Apple on this matter.

**Comment by bizz84** [comment]
With the latest changes on [develop](https://github.com/bizz84/SwiftyStoreKit/tree/develop), the shared secret is now used only by `AppeReceiptValidator`, which is a **reference implementation**.

I'm closing this as the [README](https://github.com/bizz84/SwiftyStoreKit/blob/develop/README.md) now better explains the security considerations around this.

Feel free to reopen if you feel the documentation could be improved further.
