### ISSUE TITLE
Log autorenewable subscriptions?

### ISSUE THREAD

**Issue by gerchicov-bp** [bizz84/SwiftyStoreKit#266]
### Platform

- [x] iOS

### In app purchase type

- [x] Auto-Renewable Subscription

### Environment

- [x] Sandbox (maybe production too)

### Version
0.10.2

### Issue summary
I have autorenewable subscriptions. How to log distinct purchases? I want to log each successful purchase and successful subscription renewing without duplicates.

### What did you expect to happen
Hoped to see 1-2 workable callback blocks which I could use for that purpose.

### What happened instead
`purchaseProduct` seems to be okay - user purchased one product and I got exactly one event I could post.
`completeTransactions` - may be not called, may be called with zero purchased products, may be called with a huge number of purchased products and each of them has "purchased" state. How to handle it correctly?

**Comment by mvitas** [comment]
@gerchicov-bp the scenario with auto-renewable subscriptions is specific since, based on my experience, the whole process or retrieving and analysing auto-renewing subs was not intended to handle de-duplication of data.
The important flow seems to be -> get purchases -> verify receipt -> get Expiry date -> enable/disable content/feature 
So, the main thing is to get the purchase data and being able to turn on some features for the user on request. 

My concrete case is based in tracking purchase events (appsflyer) where duplication of data can lead to wrong analytics and incorrect calculations of ROI and other KPI-s. 

As you said, complete transactions may not be called in case the user doesn't open the app for some time. Also, multiple purchases could be loaded so how to keep track which ones you already tracked on the phone (example: re-installed the app). 

So, basically (my opinion), SwiftyStoreKit, or any custom implementation that you can do yourself, will not be able to address this issue correctly with duplication of data. It was just not intended to be handled for de-dup of data on Apple side. 

What you can do, is to send the original/first purchase to your backend, where you have to implement logic to, afterwards, collect periodically data from Apple and handle your subscription validity from your backend. 
This complicates things a bit since you have to handle subscription status and purchases from your backend or with a combo backend-device after a purchase has been made. Depends on your available resources at the moment, I guess. 

Then you can send as many events to your backend as you want, duplicate etc, and your backend has to de-dup them and register if it is a new unique event and start tracking it with Apple or an old one (already tracked). Your backend becomes the extra layer for de-dup of data.

Maybe I missed something, if anyone knows a way to de-dup auto-renewing subs on the device directly, I would love to hear more about it.

**Comment by bizz84** [comment]
@mvitas I don't understand what you mean with data duplication.

Not sure if this adds value to the discussion, but the receipt always contains the most recent information about auto-renewable subscriptions.

Each time a subscription is renewed, a new receipt item is added (and can be checked).
Subscription renewal can also be detected in `completeTransactions()`.

**Comment by bb-git** [comment]
I also see some users with a huge amount of purchases. How is this happening in completeTransactions? Are also former purchases accounted? 

```
SwiftyStoreKit.completeTransactions(atomically: true) { purchases in
	    for purchase in purchases {
	        if purchase.transaction.transactionState == .purchased{
                    //code here gets often called 2x, but also saw up to 20x
                }
            }
}
```

This makes it difficult to track the real number of renewals.
