### ISSUE TITLE
Bug after merging pull request #24?

### ISSUE THREAD

**Issue by janwagner** [bizz84/SwiftyStoreKit#30]
Hi,

everytime after someone has purchased an item, the app asks for the App Store password when you send it to background and bring it back again. 

Cheers, Jan

**Comment by bizz84** [comment]
Some information relevant to this issue can be found in the [In-App Purchase Best Practices](https://developer.apple.com/library/ios/technotes/tn2387/_index.html) Technical notes from Apple. Specifically the documentation recommends the following:

**_Add a transaction queue observer at application launch_**
_StoreKit attaches your observer to the payment queue when your app calls._

I believe that this is required because a user could start a purchase and then leave or kill the app before this is completed. In such a scenario, the payment is still pending in the transaction queue, and by registering to the payment queue when the app launches it would be possible to complete the transaction and update the UI.

I'm working on a new `completeTransactions()` method that can be called from `applicationDidFinishLaunchingWithOptions()` and do the following:

* Call `finishTransaction()` on the payment queue for each received transaction. This may solve your problem as it clears the payment queue.
* Report all finished transactions to the client with a completion block. This is so that the features corresponding to the purchased IAPs can be unlocked.

That being said, users in the Apple developer forums reveal some problems with IAPs:

https://forums.developer.apple.com/thread/20194

Other than the solution I've been implementing it's a bit tricky to make IAPs work reliably and I've seen myself cases where the app keeps asking for the App Store password for a sandbox test account, even after I have removed the account from iTunes Connect.

**Comment by bizz84** [comment]
This may be the same issue as https://github.com/bizz84/SwiftyStoreKit/issues/32.

Could you read through this and see if any of the suggested steps are of any help?

http://stackoverflow.com/questions/4988663/skpaymentqueue-addtransactionobserver-asking-for-app-store-password-on-startup-a

Thanks.

**Comment by janwagner** [comment]
Your are awesome! The completeTransactions() method fixed it. After starting the app ut printed the unfinished transaction. Now everything is fine. Thx!
