### ISSUE TITLE
Cannot log into sandbox account

### ISSUE THREAD

**Issue by ArthurTam008** [bizz84/SwiftyStoreKit#304]
### Platform

- [Tick] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [Tick] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [Tick] Sandbox
- [ ] Production

### Version
ℹ Please replace this with the version of SwiftyStoreKit you're using.

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

## Report

After clicking the consumable in my app, it doesn't prompt me to log in to my sandbox account but instead pops up an error alert associated with .paymentInvalid﻿

ps, I have already logged out from iTunes in settings.

**Comment by rebeloper** [comment]
Hi, 
This issue with the sandbox testing has been around since iOS11 was in beta. Here's a workaround:

https://stackoverflow.com/a/46467498/4514671

or follow my YouTube playlist on step by step instructions on how to use SwiftyStoreKit. In a few days I'll be covering this exact same issue:

https://www.youtube.com/playlist?list=PL_csAAO9PQ8b9kqrltk2_SpYslTwyrwjb

**Comment by ArthurTam008** [comment]
That doesn't help :( 
The problem is I dont even get the chance to log in to the sandbox account.

**Comment by ArthurTam008** [comment]
Turns out I have to fill in my banking info. in iTunes connect. 
Now everything is working as expected.﻿

**Comment by rebeloper** [comment]
Great. If you need more debugging check out my other video: https://youtu.be/hcl2gqg5aJQ
Please, close this issue.
