### ISSUE TITLE
Build Error in SKProduct+LocalizedPrice.swift

### ISSUE THREAD

**Issue by wimbledon** [bizz84/SwiftyStoreKit#319]
### Platform
- [x ] iOS

### Version
0.11.1 on Xcode 8.3.3

### Related issues
#318

### Issue summary
![image](https://user-images.githubusercontent.com/3291853/34167935-407ab950-e4f4-11e7-8af6-7662f1d789bd.png)

In Version 0.11.1, localizedIntroductoryPrice was added to SKProduct (#318). However, this code is causing build error in Xcode 8.3.3 with Swift 3. Perhaps, `@available` syntax is not supported in Swift 3?

**Comment by bizz84** [comment]
I see. The problem is that `@available` is for the device OS version, not Xcode.

The headers bundled in Xcode 8 don’t include `introductoryPrice`, which is only available on Xcode 9.2 or later.

Please use pod version 0.11.0 for now. I’ll see if there is a way to make this work, or remove the code that doesn’t compile.

**Comment by bizz84** [comment]
Xcode 8 now works again with version [0.11.2](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.11.2).
