### ISSUE TITLE
product.localizedPrice crash

### ISSUE THREAD

**Issue by foolbear** [bizz84/SwiftyStoreKit#355]
### Platform

- [* ] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [* ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [* ] Sandbox
- [ ] Production

### Version
ℹ Please replace this with the version of SwiftyStoreKit you're using.

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
ℹ Please replace this with an explanation of the issue, including reproduction steps.

product.localizedPrice crash when  initiates an in-app purchase on the App Store

SwiftyStoreKit.shouldAddStorePaymentHandler =  { payment, product in
let localizedPrice = product.localizedPrice
}

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by Sam-Spencer** [comment]
Did you ever find out what was going on? The latest release doesn't appear to have this issue...

**Comment by gesabo** [comment]
im having this issue trying to get through app review. App Review is sending me crash logs that aren't fully symbolicated but the first call is `0   libswiftFoundation.dylib      	0x000000019a3ce364 static Locale._unconditionallyBridgeFromObjectiveC+ 688996 (_:) + 252` which looking around seems to be related to this price locale bug.  This app is iOS only so not sure why it's still an issue? I'm trying to install 0.16.3 to see if its been fixed but currently cannot due to `Cannot override 'paymentQueue' which has been marked unavailable` which looks like its related to this being commented out: 

// ```
#if os(iOS) && !targetEnvironment(macCatalyst)
    func paymentQueue(_ queue: SKPaymentQueue, shouldAddStorePayment payment: SKPayment, for product: SKProduct) -> Bool {
        return shouldAddStorePaymentHandler?(payment, product) ?? false
    }
    // #endif
```
