### ISSUE TITLE
refresh receipt and validate afterwards

### ISSUE THREAD

**Issue by bb-git** [bizz84/SwiftyStoreKit#42]
So if I understand right, I can refresh the receipt if there is no receipt present, while verifying the receipt with: `SwiftyStoreKit.refreshReceipt`

But after doing this, would't it be right to verify the refreshed receipt again calling 
`SwiftyStoreKit.verifyReceipt` ?

But in the completion handler I cannot access the product the receipts belongs to. I have nonconsumable products and autorenewing subscriptions, so I'm not able to choose the right verification method. 

In your example you just refresh the receipt without doing anything with it, what's the purpose of this?

Thanks

**Comment by bizz84** [comment]
Apologies for the very late reply.

I have reviewed the code as I didn't implement this entirely myself. From what I can understand:

- you can call `verifyReceipt()` to retrieve the receipt as a dictionary. If this is successful you can test each non consumable product and autorenewing subscription individually against the receipt with the `SwiftyStoreKit.verifyPurchase()` and `SwiftyStoreKit.verifySubscription()` methods.
- If no receipt is found, you can try to call `refreshReceipt()`, however note that this is implemented differently for iOS/tvOS and OS X.
- If `refreshReceipt()` succeeds, maybe it makes sense to call `verifyReceipt()` again as you mentioned. 

Ideally I would like this API to be a bit better so that you don't have to make three calls.

**Comment by bizz84** [comment]
This has now been fixed on [release 0.10.0](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.10.0)
