### ISSUE TITLE
Why is UI confirmation different during testing?

### ISSUE THREAD

**Issue by pj4533** [bizz84/SwiftyStoreKit#472]
I am testing my apps first in-app purchase but I have never used StoreKit before.  When I use SwiftyStoreKit for a non-consumable, it all works, I get a screen like this:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/110283/59047070-2ff7ac80-8851-11e9-91a8-2d766eff3b03.png">

Why doesn't it look like other in-app purchases I see on the App Store? Such as this:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/110283/59047131-4a318a80-8851-11e9-8321-2bbce61e40d8.png">

Is that due to being in TestFlight? Or do I need to implement something to get that nice sheet UI?

**Comment by danramteke** [comment]
Yes that is due to TestFlight.

**Comment by Sam-Spencer** [comment]
Hi @pj4533, this occurs because of how in-App Purchases are authorized when testing in the iOS Simulator, on a device, or via TestFlight. This is a result of Apple's implementation and system-level auth-flow rather than a detail of SwiftyStoreKit. 

Rest assured, when publishing to the App Store your users will see the nice sheet you're expecting.
