### ISSUE TITLE
Purchase and product delivery does not seem to be atomic

### ISSUE THREAD

**Issue by kenjitayama** [bizz84/SwiftyStoreKit#50]
Hi, I'm planning to use SwiftyStoreKit in my app, but I have concerns about the following lines:
https://github.com/bizz84/SwiftyStoreKit/blob/ee0def276b170e917a0e80d8eb29d2d614fe327a/SwiftyStoreKit/InAppProductPurchaseRequest.swift#L112-L117

`finishTransaction` is called before any product is delivered. 
I think there is a risk that the user will be charged without the product being delivered, especially if the product is a consumable type.
Is this risk handled somewhere else in the library?

The API docs also says that [finishTransaction](https://developer.apple.com/library/ios/documentation/StoreKit/Reference/SKPaymentQueue_Class/#//apple_ref/occ/instm/SKPaymentQueue/finishTransaction:) should be called after product delivery.
```
Your application should call finishTransaction: only after it has successfully processed the transaction and unlocked the functionality purchased by the user.
```

**Comment by bizz84** [comment]
The method `func paymentQueue(queue:updatedTransactions:)` should only ever be called if a product was previously purchased or a restore purchases call was made.

This may happen if the user started a purchase during the current app section, or even if the purchase was completed after the app was closed. The latter case is possible because the purchase flow can continue even after the app is terminated. 

Note that clients should call `completeTransactions()` as soon as the app start to be notified of any completed payments (see [README](https://github.com/bizz84/SwiftyStoreKit/blob/master/README.md)).

**Comment by kenjitayama** [comment]
@bizz84 
I understand why `completeTransactions()` must be called on launch, but I'm trying to explain a different problem.
I'd like to write an example of what might happen.

When buying a gem (virtual currency) inside a game:

1. User taps purchase button
2. Purchase request is sent with `SwiftyStoreKit.purchaseProduct`
3. `SKPaymentTransactionObserver` receives a success result with `func paymentQueue(queue:updatedTransactions:)`
4. `paymentQueue.finishTransaction(transaction)` is called immediately
5. An HTTP request is sent to the game server to increase the user's gem balance.
6. The request fails for some reason.
7. The user is charged for the purchase, but does not get the gem.

This is why I think `paymentQueue.finishTransaction(transaction)` should not be called immediately.
The [API docs](https://developer.apple.com/library/ios/documentation/StoreKit/Reference/SKPaymentQueue_Class/#//apple_ref/occ/instm/SKPaymentQueue/finishTransaction:) also says so.

**Comment by bizz84** [comment]
I understand now. The first step would be to hold a list of transactions for `.Purchased` and `.Restored` and call `finishTransaction()` after the callback has been called:
```swift
        if transactionResults.count > 0 {
            dispatch_async(dispatch_get_main_queue()) {
                self.callback(results: transactionResults)
            }
        }
        for transaction in transactions {
            paymentQueue.finishTransaction(transaction)
        }
```
This guarantees that your callback is called before `finishTransaction()` but it still means that your HTTP request may still fail and the user would be charged. I can think of two solutions:
* Your app keeps track that the purchase has happened and tries to re-deliver the content later on
* We add a `finishTransactions()` call to SwiftyStoreKit so that your app can call this when the content has been delivered. I believe this would be a fragile API because if the client forgets to call `finishTransactions()`, the transactions will remain pending in the payment queue and this may cause problems with future purchases. What do you think?

**Comment by kenjitayama** [comment]
I was thinking of calling `paymentQueue.finishTransaction(transaction)` after receiving a successful HTTP response from the game server.
But after some more thoughts, I realized this approach gets pretty complicated:

What if the gem increase was done in the game server, but the client failed to receive the response?
The `SKPaymentTransaction` is still active, so the app gets to send another gem increase request to the game server.
To prevent delivering the gems twice, the game server needs to check if the receipt had already been processed.
But if it was already processed, what kind of message should we show to the user, or is it ok to keep silent?
Pretty complicated.

I am beginning to think that it might be practical to call `paymentQueue.finishTransaction(transaction)` immediately, and rely on the "restore purchases" feature, despite what the API docs says to do.
I'm going to take this approach in my app for now.
With this approach, there is no need to modify SwiftyStoreKit.
