### ISSUE TITLE
Store hack

### ISSUE THREAD

**Issue by goktugyil** [bizz84/SwiftyStoreKit#66]
http://blog.gameanalytics.com/blog/how-to-detect-and-prevent-in-app-purchase-hacks.html

Something similar happened to me, a user apparently bought like 200 purchases in 10 minutes and I don't see that money in itunes connect. 

```
        func alertForPurchaseResult(result: SwiftyStoreKit.PurchaseResult) -> UIAlertController {
            switch result {
            case .Success(let productId):
                    //got in there
```

Why is this happening? How can we fix this issue?

**Comment by tosbaha** [comment]
You should do what is called receipt validation. I suggest you do the verification on server side. Since some hacks also allows bypassing local verification. In order to verify receipt on server, you send your receipt in base64encoded to apple servers and check the result for

- Correct server response
- Your bundleId
- Your in_app array
  - Is it empty?
  - Does it have the values user bought

Good luck. Kolay gelsin 👍 Bir Türke yardımımız dokunduysa ne mutlu bize :)

**Comment by goktugyil** [comment]
Thanks, I expected something like this to be done in Apple's frameworks automatically.

**Comment by bizz84** [comment]
Local receipt verification is being tracked here: #101 

Closing this issue for now. @goktugyil If needed, feel free to reopen.

**Comment by shabani0012** [comment]
How can I get brawl pirate bot
