### ISSUE TITLE
App store constantly asking for password, even if I cancel the it.

### ISSUE THREAD

**Issue by aksswami** [bizz84/SwiftyStoreKit#67]
I am implementing an in-app purchase with consumable products. The problem I am facing is dialogue box asking for password constantly start appearing, even if I cancel, it pop up again.

While debugging I found that `finishTransaction is not called` in `InAppCompleteTransactionObserver`.

Below method didn't call complete transaction on `callbackCalled = true`, which is causing dialogue box to appear again and again.

```
func paymentQueue(queue: SKPaymentQueue, updatedTransactions transactions: [SKPaymentTransaction]) {

        if callbackCalled {
            return
        }
        if SwiftyStoreKit.hasInFlightPayments {
            return
        }

        var completedTransactions: [SwiftyStoreKit.CompletedTransaction] = []

        for transaction in transactions {

            #if os(iOS) || os(tvOS)
                let transactionState = transaction.transactionState
            #elseif os(OSX)
                let transactionState = PaymentTransactionState(rawValue: transaction.transactionState)!
            #endif

            if transactionState != .Purchasing {

                let completedTransaction = SwiftyStoreKit.CompletedTransaction(productId: transaction.payment.productIdentifier, transactionState: transactionState)

                completedTransactions.append(completedTransaction)

                print("Finishing transaction for payment \"\(transaction.payment.productIdentifier)\" with state: \(transactionState.stringValue)")

                paymentQueue.finishTransaction(transaction)
            }
        }
        callbackCalled = true

        callback(completedTransactions: completedTransactions)
    }
```

**Comment by hi-guy** [comment]
Same. Appear again and again

**Comment by bizz84** [comment]
@aksswami Apologies for the late reply.

So you're saying that the debugger reaches the `callbackCalled = true` line, but `finishTransaction` is not called. With the code above, this can only happen if `transactionState == .Purchasing`.

The `SKPaymentTransactionState` type is defined as:
```
@available(iOS 3.0, *)
public enum SKPaymentTransactionState : Int {
    
    case Purchasing // Transaction is being added to the server queue.
    case Purchased // Transaction is in queue, user has been charged.  Client should complete the transaction.
    case Failed // Transaction was cancelled or failed before being added to the server queue.
    case Restored // Transaction was restored from user's purchase history.  Client should complete the transaction.
    @available(iOS 8.0, *)
    case Deferred // The transaction is in the queue, but its final status is pending external action.
}
```

So it would appear that if a transaction is `.Purchased`, `.Failed` or `.Restored`, then we should call `finishTransaction`, otherwise not.

Is it possible that you initiated the transaction when you were logged in with an Apple ID, then signed out, logged in with a different Apple ID, and then ran the app?

I have seen problems like this before and some people have experienced the same. Some examples:

http://stackoverflow.com/questions/34936912/ios-sandbox-test-account-keeps-asking-to-sign-in-after-app-exit
http://stackoverflow.com/questions/36957038/ios-app-asks-for-password-every-time-it-is-launched

Could you run the debugger and check what is the `transactionState` in the for loop above?

**Comment by bizz84** [comment]
@aksswami can you retest this with the latest SwiftyStoreKit?

The purchase flows have been improved considerably since this issue was opened.

I will close this in a few weeks if there are no updates.

**Comment by Dino4674** [comment]
If there are no updated transactions, this callback will not be called. In am depending on it on app startup to continue with app logic. But if it is not being called, my app is stuck.

Why can not this callback be called with empty products array?

public class func completeTransactions(atomically: Bool = true, completion: @escaping ([Product]) -> ()) {
        sharedInstance.completeTransactionsObserver = InAppCompleteTransactionsObserver(atomically: atomically, callback: completion)
    }

**Comment by aksswami** [comment]
@bizz84 Not facing this issue with the latest SwiftyStoreKit. Thanks for help.

**Comment by bizz84** [comment]
@Dino4674 apologies for the late reply. 

You only receive a callback from `completeTransactions()` if the payment queue is updated by StoreKit and the updated transactions don't belong to a purchase or restore purchase call.

As this is not guaranteed to be called, your app should not wait for it to complete.

If it is called, you can use it to unlock functionality in the app.

I'm closing this issue as this should be fixed in the newer versions of SwiftyStoreKit.
